# Generated by Django 3.0.5 on 2020-04-26 22:25

from django.db import migrations, models
import django.db.models.deletion
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FactorPerdida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('factor', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Generador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GraficoMatplotlib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fig', django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
        migrations.AddField(
            model_name='codigo',
            name='auxiliar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='codigo',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='factorperdida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.FactorPerdida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='generador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Generador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente'),
            preserve_default=False,
        ),
    ]
