# Generated by Django 3.0.5 on 2020-04-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200426_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barra',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='GraficoMatplotlib',
        ),
        migrations.RemoveField(
            model_name='codigo',
            name='auxiliar',
        ),
        migrations.RemoveField(
            model_name='codigo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='codigo',
            name='factorperdida',
        ),
        migrations.RemoveField(
            model_name='codigo',
            name='generador',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='activo',
        ),
        migrations.DeleteModel(
            name='Barra',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='FactorPerdida',
        ),
        migrations.DeleteModel(
            name='Generador',
        ),
    ]
