# Generated by Django 3.0.5 on 2020-04-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_graficomatplotlib'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graficomatplotlib',
            old_name='figure',
            new_name='fig',
        ),
    ]
