# Generated by Django 3.0.5 on 2020-04-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200426_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
