# Generated by Django 3.0.5 on 2020-04-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_periodo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='activo',
            field=models.IntegerField(default=0),
        ),
    ]
