# Generated by Django 3.0.5 on 2020-04-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200427_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratomes',
            name='mesano',
        ),
        migrations.AddField(
            model_name='periodo',
            name='fecha',
            field=models.DateField(default=1, verbose_name='Mes'),
            preserve_default=False,
        ),
    ]
