# Generated by Django 3.0.5 on 2020-04-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_remove_contratomes_mesano'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='fecha',
            field=models.DateField(default='2020/01/01', verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
