# Generated by Django 3.0.5 on 2020-04-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200427_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='fecha',
        ),
    ]
