# Generated by Django 3.0.5 on 2020-05-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0053_auto_20200511_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='area',
        ),
    ]
