# Generated by Django 3.0.5 on 2020-04-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200426_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorPerdidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('factor', models.FloatField(default=1)),
            ],
        ),
    ]
