# Generated by Django 3.0.5 on 2020-04-27 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_codigo_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='auxiliar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codigo',
            name='factorperdidas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.FactorPerdidas'),
            preserve_default=False,
        ),
    ]
