# Generated by Django 3.0.5 on 2020-04-27 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200426_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente'),
            preserve_default=False,
        ),
    ]
