# Generated by Django 3.0.5 on 2020-04-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_graficomatplotlib'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraficoMatplotlib',
        ),
    ]
