# Generated by Django 3.0.5 on 2020-04-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_delete_graficomatplotlib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='signo',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
