# Generated by Django 3.0.5 on 2020-04-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200427_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarraTransferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('barra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Barra')),
            ],
        ),
    ]
