# Generated by Django 3.0.5 on 2020-04-28 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_barra_barratransferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente')),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Generador')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('licitacion', models.BooleanField(default=True)),
                ('regulado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('fechaini', models.DateField(verbose_name='Fecha inicio')),
                ('fechafin', models.DateField(verbose_name='Fecha fin')),
                ('fija', models.FloatField(default=0)),
                ('variable', models.FloatField(default=0)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Contrato')),
                ('mesano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Periodo')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipocontrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TipoContrato'),
        ),
    ]
