# Generated by Django 3.0.5 on 2020-04-28 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200427_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='generador',
        ),
        migrations.AddField(
            model_name='contratomes',
            name='generador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Generador'),
            preserve_default=False,
        ),
    ]
