# Generated by Django 3.0.5 on 2020-04-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_periodo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Modelo'),
            preserve_default=False,
        ),
    ]
