# Generated by Django 3.0.5 on 2020-04-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_contrato_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='visualizar',
            field=models.BooleanField(default=True),
        ),
    ]
