# Generated by Django 3.0.5 on 2020-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20200428_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='bilateral',
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Licitación'), (1, 'Bilateral'), (2, 'C.Libres')], default=1),
        ),
    ]
