# Generated by Django 3.0.5 on 2020-04-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20200430_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='codigo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
