# Generated by Django 3.0.5 on 2020-04-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_remove_contrato_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratomes',
            name='codigo',
        ),
    ]
