# Generated by Django 3.0.5 on 2020-04-30 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_remove_contratomes_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='barra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Barra'),
            preserve_default=False,
        ),
    ]
