# Generated by Django 3.0.5 on 2020-04-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_contrato_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomes',
            name='fijafp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contratomes',
            name='variablefp',
            field=models.FloatField(default=0),
        ),
    ]
