# Generated by Django 3.0.5 on 2020-05-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20200430_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='signo',
            field=models.IntegerField(choices=[(1, 'Total'), (2, 'Mercado Libre')], default=1),
        ),
    ]
