# Generated by Django 3.0.5 on 2020-05-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20200430_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='signo',
            field=models.BooleanField(default=True),
        ),
    ]
