# Generated by Django 3.0.5 on 2020-05-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20200430_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
    ]
