# Generated by Django 3.0.5 on 2020-05-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_registro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='codigo',
            field=models.IntegerField(default=1),
        ),
    ]
