# Generated by Django 3.0.5 on 2020-05-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20200430_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigo',
            name='factorperdidas',
        ),
    ]
