# Generated by Django 3.0.5 on 2020-05-02 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_remove_codigo_factorperdidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='barra',
            name='factorperdidas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.FactorPerdidas'),
            preserve_default=False,
        ),
    ]
