# Generated by Django 3.0.5 on 2020-05-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_barra_factorperdidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='potencia',
            field=models.BooleanField(default=False),
        ),
    ]
