# Generated by Django 3.0.5 on 2020-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_registro_potencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigo',
            old_name='auxiliar',
            new_name='auxiliar1',
        ),
        migrations.AddField(
            model_name='codigo',
            name='auxiliar2',
            field=models.IntegerField(default=0),
        ),
    ]
