# Generated by Django 3.0.5 on 2020-05-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_auto_20200502_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
