# Generated by Django 3.0.5 on 2020-05-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_auto_20200502_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='mesano',
            field=models.DateField(verbose_name='Vigencia'),
        ),
    ]
