# Generated by Django 3.0.5 on 2020-05-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_auto_20200502_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dia')),
                ('habil', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
