# Generated by Django 3.0.5 on 2020-05-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_dias_ddmmyyyy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dias',
        ),
    ]
