# Generated by Django 3.0.5 on 2020-05-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_delete_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dia')),
                ('habil', models.BooleanField(default=True)),
                ('ddmmyyyy', models.CharField(max_length=10)),
            ],
        ),
    ]
