# Generated by Django 3.0.5 on 2020-05-05 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_reparto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparto',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Modelo'),
            preserve_default=False,
        ),
    ]
