# Generated by Django 3.0.5 on 2020-05-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_reparto_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparto',
            name='energiafp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reparto',
            name='energiahp',
            field=models.FloatField(default=0),
        ),
    ]
