# Generated by Django 3.0.5 on 2020-05-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_auto_20200505_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomes',
            name='codid',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
