# Generated by Django 3.0.5 on 2020-05-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_contratomes_codid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomes',
            name='codid',
            field=models.IntegerField(default=1),
        ),
    ]
