# Generated by Django 3.0.5 on 2020-05-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_auto_20200506_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparto',
            name='codid',
            field=models.IntegerField(default=1),
        ),
    ]
