# Generated by Django 3.0.5 on 2020-05-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_reparto_codid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparto',
            name='porcentaje',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reparto',
            name='porcentajefp',
            field=models.FloatField(default=0),
        ),
    ]
