# Generated by Django 3.0.5 on 2020-05-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_auto_20200506_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='maxdemandadia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='periodo',
            name='maxdemandahora',
            field=models.IntegerField(default=0),
        ),
    ]
