# Generated by Django 3.0.5 on 2020-05-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0052_auto_20200509_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('barra00', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra00', to='polls.Barra')),
                ('barra01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra01', to='polls.Barra')),
                ('barra02', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra02', to='polls.Barra')),
                ('barra03', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra03', to='polls.Barra')),
                ('barra04', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra04', to='polls.Barra')),
                ('barra05', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra05', to='polls.Barra')),
                ('barra06', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra06', to='polls.Barra')),
                ('barra07', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra07', to='polls.Barra')),
                ('barra08', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra08', to='polls.Barra')),
                ('barra09', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra09', to='polls.Barra')),
                ('barra10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra10', to='polls.Barra')),
                ('barra11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra11', to='polls.Barra')),
                ('barra12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra12', to='polls.Barra')),
                ('barra13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra13', to='polls.Barra')),
                ('barra14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra14', to='polls.Barra')),
                ('barra15', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra15', to='polls.Barra')),
            ],
        ),
    ]
