# Generated by Django 3.0.5 on 2020-05-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0054_area_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Area'),
            preserve_default=False,
        ),
    ]
