# Generated by Django 3.0.5 on 2020-05-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0055_contrato_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='clase',
            field=models.IntegerField(choices=[(0, 'Ninguna'), (1, 'Selección')], default=1),
        ),
    ]
