# Generated by Django 3.0.5 on 2020-05-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0057_auto_20200511_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='modo',
            field=models.IntegerField(choices=[(1, '+'), (-1, '-')], default=1),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='signo',
            field=models.BooleanField(default=True),
        ),
    ]
