# Generated by Django 3.0.5 on 2020-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0058_auto_20200511_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='modo',
            field=models.BooleanField(choices=[(True, '+'), (False, '-')], default=True),
        ),
    ]
