# Generated by Django 3.0.5 on 2020-05-12 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0059_auto_20200511_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('clave2', models.CharField(max_length=50)),
                ('modelos', models.CharField(max_length=200)),
                ('modo', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.DeleteModel(
            name='TipoContrato',
        ),
        migrations.AddField(
            model_name='area',
            name='usuario0',
            field=models.CharField(default='2020-01-01', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barra',
            name='usuario0',
            field=models.CharField(default=datetime.date(2020, 5, 12), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barratransferencia',
            name='usuario0',
            field=models.CharField(default=datetime.date(2020, 5, 12), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='usuario0',
            field=models.CharField(default=datetime.date(2020, 5, 12), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario0',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratomes',
            name='usuario0',
            field=models.CharField(default=datetime.date(2020, 5, 12), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factorperdidas',
            name='usuario0',
            field=models.CharField(default=datetime.date(2020, 5, 12), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='usuario0',
            field=models.CharField(default=datetime.date(2020, 5, 12), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='usuario0',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reparto',
            name='usuario0',
            field=models.CharField(default=datetime.date(2020, 5, 12), max_length=200),
            preserve_default=False,
        ),
    ]
