# Generated by Django 3.0.5 on 2020-05-12 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0060_auto_20200512_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='fecha0',
            field=models.DateField(default=datetime.date(2020, 5, 12), verbose_name='fecha actualizado'),
            preserve_default=False,
        ),
    ]
