# Generated by Django 3.0.5 on 2020-05-12 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0062_factorperdidas_fecha0'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='fecha0',
            field=models.DateField(default=datetime.date(2020, 5, 12), verbose_name='fecha actualizado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barra',
            name='fecha0',
            field=models.DateField(default=datetime.date(2020, 5, 12), verbose_name='fecha actualizado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barratransferencia',
            name='fecha0',
            field=models.DateField(default=datetime.date(2020, 5, 12), verbose_name='fecha actualizado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='fecha0',
            field=models.DateField(default=datetime.date(2020, 5, 12), verbose_name='fecha actualizado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha0',
            field=models.DateField(default=datetime.date(2020, 5, 12), verbose_name='fecha actualizado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratomes',
            name='fecha0',
            field=models.DateField(default=datetime.date(2020, 5, 12), verbose_name='fecha actualizado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha0',
            field=models.DateField(default=datetime.date(2020, 5, 12), verbose_name='fecha actualizado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reparto',
            name='fecha0',
            field=models.DateField(default=datetime.date(2020, 5, 12), verbose_name='fecha actualizado'),
            preserve_default=False,
        ),
    ]
