# Generated by Django 3.0.5 on 2020-05-12 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0065_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barratransferencia',
            name='fecha0',
            field=models.DateTimeField(verbose_name='fecha actualizado'),
        ),
        migrations.AlterField(
            model_name='factorperdidas',
            name='fecha0',
            field=models.DateTimeField(verbose_name='fecha actualizado'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='fecha0',
            field=models.DateTimeField(verbose_name='fecha actualizado'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha0',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
