# Generated by Django 3.0.5 on 2020-04-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_mymodelwithfigure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodelwithfigure',
            old_name='fig',
            new_name='figure',
        ),
    ]
