# Generated by Django 3.0.5 on 2020-04-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200424_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodelwithfigure',
            old_name='figure',
            new_name='fig',
        ),
    ]
